#                                    Create and visualize "numpy" array

## Importing necessary library

In [1]:
import numpy as np

In [2]:
rand_int = np.random.randint(1, 100, (10, 3))

### My numpy array is

In [3]:
print("my array is:", rand_int)

my array is: [[80 57 69]
 [13 43 64]
 [93 52 95]
 [20 43 53]
 [96  5 74]
 [98 97 60]
 [50 44 65]
 [15 88 27]
 [94 96 67]
 [18 95 25]]
