In [2]:
!pip3 install numpy

  Using cached numpy-1.23.3-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)


In [3]:
import numpy as np

In [6]:
rand_int = np.random.randint(1, 100, (10, 3))

In [7]:
print("my array is:", rand_int)

my array is: [[47 74 61]
 [81 12 18]
 [19 74 31]
 [40 46 88]
 [12 40 69]
 [28  6 80]
 [38 56 51]
 [18 16 70]
 [58  6 63]
 [21 31 14]]
