#                                    Create and visualize "numpy" array

## Importing necessary library

In [1]:
import numpy as np

In [4]:
rand_int = np.random.randint(1, 100, (10, 3))

### My numpy array is

In [5]:
print("my array is:", rand_int)

my array is: [[ 1 72 41]
 [85 89 15]
 [54 19 73]
 [76 94 48]
 [45 97  6]
 [67 95 29]
 [96 15  9]
 [17 71 11]
 [22 74 44]
 [32 13 18]]
